/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ContextListEnvironmentVariablesResponseItemsInner
 */
public class ContextListEnvironmentVariablesResponseItemsInnerTest {
    private final ContextListEnvironmentVariablesResponseItemsInner model = new ContextListEnvironmentVariablesResponseItemsInner();

    /**
     * Model tests for ContextListEnvironmentVariablesResponseItemsInner
     */
    @Test
    public void testContextListEnvironmentVariablesResponseItemsInner() {
        // TODO: test ContextListEnvironmentVariablesResponseItemsInner
    }

    /**
     * Test the property 'variable'
     */
    @Test
    public void variableTest() {
        // TODO: test variable
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'contextId'
     */
    @Test
    public void contextIdTest() {
        // TODO: test contextId
    }

}
