/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InsightsGetProjectWorkflowJobMetricsResponseItemsInnerMetricsDurationMetrics
 */
public class InsightsGetProjectWorkflowJobMetricsResponseItemsInnerMetricsDurationMetricsTest {
    private final InsightsGetProjectWorkflowJobMetricsResponseItemsInnerMetricsDurationMetrics model = new InsightsGetProjectWorkflowJobMetricsResponseItemsInnerMetricsDurationMetrics();

    /**
     * Model tests for InsightsGetProjectWorkflowJobMetricsResponseItemsInnerMetricsDurationMetrics
     */
    @Test
    public void testInsightsGetProjectWorkflowJobMetricsResponseItemsInnerMetricsDurationMetrics() {
        // TODO: test InsightsGetProjectWorkflowJobMetricsResponseItemsInnerMetricsDurationMetrics
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

    /**
     * Test the property 'mean'
     */
    @Test
    public void meanTest() {
        // TODO: test mean
    }

    /**
     * Test the property 'median'
     */
    @Test
    public void medianTest() {
        // TODO: test median
    }

    /**
     * Test the property 'p95'
     */
    @Test
    public void p95Test() {
        // TODO: test p95
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'standardDeviation'
     */
    @Test
    public void standardDeviationTest() {
        // TODO: test standardDeviation
    }

}
