/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerMetrics;
import com.konfigthis.client.model.InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataInnerTrends;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InsightsGetProjectSummaryMetricsResponseProjectWorkflowBranchDataInner
 */
public class InsightsGetProjectSummaryMetricsResponseProjectWorkflowBranchDataInnerTest {
    private final InsightsGetProjectSummaryMetricsResponseProjectWorkflowBranchDataInner model = new InsightsGetProjectSummaryMetricsResponseProjectWorkflowBranchDataInner();

    /**
     * Model tests for InsightsGetProjectSummaryMetricsResponseProjectWorkflowBranchDataInner
     */
    @Test
    public void testInsightsGetProjectSummaryMetricsResponseProjectWorkflowBranchDataInner() {
        // TODO: test InsightsGetProjectSummaryMetricsResponseProjectWorkflowBranchDataInner
    }

    /**
     * Test the property 'workflowName'
     */
    @Test
    public void workflowNameTest() {
        // TODO: test workflowName
    }

    /**
     * Test the property 'branch'
     */
    @Test
    public void branchTest() {
        // TODO: test branch
    }

    /**
     * Test the property 'metrics'
     */
    @Test
    public void metricsTest() {
        // TODO: test metrics
    }

    /**
     * Test the property 'trends'
     */
    @Test
    public void trendsTest() {
        // TODO: test trends
    }

}
