/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner;
import com.konfigthis.client.model.InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InsightsGetProjectWorkflowTestMetricsResponse
 */
public class InsightsGetProjectWorkflowTestMetricsResponseTest {
    private final InsightsGetProjectWorkflowTestMetricsResponse model = new InsightsGetProjectWorkflowTestMetricsResponse();

    /**
     * Model tests for InsightsGetProjectWorkflowTestMetricsResponse
     */
    @Test
    public void testInsightsGetProjectWorkflowTestMetricsResponse() {
        // TODO: test InsightsGetProjectWorkflowTestMetricsResponse
    }

    /**
     * Test the property 'averageTestCount'
     */
    @Test
    public void averageTestCountTest() {
        // TODO: test averageTestCount
    }

    /**
     * Test the property 'mostFailedTests'
     */
    @Test
    public void mostFailedTestsTest() {
        // TODO: test mostFailedTests
    }

    /**
     * Test the property 'mostFailedTestsExtra'
     */
    @Test
    public void mostFailedTestsExtraTest() {
        // TODO: test mostFailedTestsExtra
    }

    /**
     * Test the property 'slowestTests'
     */
    @Test
    public void slowestTestsTest() {
        // TODO: test slowestTests
    }

    /**
     * Test the property 'slowestTestsExtra'
     */
    @Test
    public void slowestTestsExtraTest() {
        // TODO: test slowestTestsExtra
    }

    /**
     * Test the property 'totalTestRuns'
     */
    @Test
    public void totalTestRunsTest() {
        // TODO: test totalTestRuns
    }

    /**
     * Test the property 'testRuns'
     */
    @Test
    public void testRunsTest() {
        // TODO: test testRuns
    }

}
