/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InsightsGetJobTimeseriesDataResponseItemsInnerMetricsDurationMetrics;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InsightsGetJobTimeseriesDataResponseItemsInnerMetrics
 */
public class InsightsGetJobTimeseriesDataResponseItemsInnerMetricsTest {
    private final InsightsGetJobTimeseriesDataResponseItemsInnerMetrics model = new InsightsGetJobTimeseriesDataResponseItemsInnerMetrics();

    /**
     * Model tests for InsightsGetJobTimeseriesDataResponseItemsInnerMetrics
     */
    @Test
    public void testInsightsGetJobTimeseriesDataResponseItemsInnerMetrics() {
        // TODO: test InsightsGetJobTimeseriesDataResponseItemsInnerMetrics
    }

    /**
     * Test the property 'totalRuns'
     */
    @Test
    public void totalRunsTest() {
        // TODO: test totalRuns
    }

    /**
     * Test the property 'failedRuns'
     */
    @Test
    public void failedRunsTest() {
        // TODO: test failedRuns
    }

    /**
     * Test the property 'successfulRuns'
     */
    @Test
    public void successfulRunsTest() {
        // TODO: test successfulRuns
    }

    /**
     * Test the property 'throughput'
     */
    @Test
    public void throughputTest() {
        // TODO: test throughput
    }

    /**
     * Test the property 'medianCreditsUsed'
     */
    @Test
    public void medianCreditsUsedTest() {
        // TODO: test medianCreditsUsed
    }

    /**
     * Test the property 'totalCreditsUsed'
     */
    @Test
    public void totalCreditsUsedTest() {
        // TODO: test totalCreditsUsed
    }

    /**
     * Test the property 'durationMetrics'
     */
    @Test
    public void durationMetricsTest() {
        // TODO: test durationMetrics
    }

}
