/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
 */
public class InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCountsTest {
    private final InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts model = new InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts();

    /**
     * Model tests for InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
     */
    @Test
    public void testInsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts() {
        // TODO: test InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'failure'
     */
    @Test
    public void failureTest() {
        // TODO: test failure
    }

    /**
     * Test the property 'skipped'
     */
    @Test
    public void skippedTest() {
        // TODO: test skipped
    }

    /**
     * Test the property 'success'
     */
    @Test
    public void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
