/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InsightsGetFlakyTestsResponseFlakyTestsInner
 */
public class InsightsGetFlakyTestsResponseFlakyTestsInnerTest {
    private final InsightsGetFlakyTestsResponseFlakyTestsInner model = new InsightsGetFlakyTestsResponseFlakyTestsInner();

    /**
     * Model tests for InsightsGetFlakyTestsResponseFlakyTestsInner
     */
    @Test
    public void testInsightsGetFlakyTestsResponseFlakyTestsInner() {
        // TODO: test InsightsGetFlakyTestsResponseFlakyTestsInner
    }

    /**
     * Test the property 'timeWasted'
     */
    @Test
    public void timeWastedTest() {
        // TODO: test timeWasted
    }

    /**
     * Test the property 'workflowCreatedAt'
     */
    @Test
    public void workflowCreatedAtTest() {
        // TODO: test workflowCreatedAt
    }

    /**
     * Test the property 'workflowId'
     */
    @Test
    public void workflowIdTest() {
        // TODO: test workflowId
    }

    /**
     * Test the property 'classname'
     */
    @Test
    public void classnameTest() {
        // TODO: test classname
    }

    /**
     * Test the property 'pipelineNumber'
     */
    @Test
    public void pipelineNumberTest() {
        // TODO: test pipelineNumber
    }

    /**
     * Test the property 'workflowName'
     */
    @Test
    public void workflowNameTest() {
        // TODO: test workflowName
    }

    /**
     * Test the property 'testName'
     */
    @Test
    public void testNameTest() {
        // TODO: test testName
    }

    /**
     * Test the property 'jobName'
     */
    @Test
    public void jobNameTest() {
        // TODO: test jobName
    }

    /**
     * Test the property 'jobNumber'
     */
    @Test
    public void jobNumberTest() {
        // TODO: test jobNumber
    }

    /**
     * Test the property 'timesFlaked'
     */
    @Test
    public void timesFlakedTest() {
        // TODO: test timesFlaked
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property '_file'
     */
    @Test
    public void _fileTest() {
        // TODO: test _file
    }

}
