/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InsightsGetProjectWorkflowMetricsResponseItemsInnerMetrics;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InsightsGetProjectWorkflowMetricsResponseItemsInner
 */
public class InsightsGetProjectWorkflowMetricsResponseItemsInnerTest {
    private final InsightsGetProjectWorkflowMetricsResponseItemsInner model = new InsightsGetProjectWorkflowMetricsResponseItemsInner();

    /**
     * Model tests for InsightsGetProjectWorkflowMetricsResponseItemsInner
     */
    @Test
    public void testInsightsGetProjectWorkflowMetricsResponseItemsInner() {
        // TODO: test InsightsGetProjectWorkflowMetricsResponseItemsInner
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'metrics'
     */
    @Test
    public void metricsTest() {
        // TODO: test metrics
    }

    /**
     * Test the property 'windowStart'
     */
    @Test
    public void windowStartTest() {
        // TODO: test windowStart
    }

    /**
     * Test the property 'windowEnd'
     */
    @Test
    public void windowEndTest() {
        // TODO: test windowEnd
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

}
