/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.JobGetDetailsResponseContextsInner;
import com.konfigthis.client.model.JobGetDetailsResponseExecutor;
import com.konfigthis.client.model.JobGetDetailsResponseLatestWorkflow;
import com.konfigthis.client.model.JobGetDetailsResponseMessagesInner;
import com.konfigthis.client.model.JobGetDetailsResponseOrganization;
import com.konfigthis.client.model.JobGetDetailsResponseParallelRunsInner;
import com.konfigthis.client.model.JobGetDetailsResponsePipeline;
import com.konfigthis.client.model.JobGetDetailsResponseProject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for JobGetDetailsResponse
 */
public class JobGetDetailsResponseTest {
    private final JobGetDetailsResponse model = new JobGetDetailsResponse();

    /**
     * Model tests for JobGetDetailsResponse
     */
    @Test
    public void testJobGetDetailsResponse() {
        // TODO: test JobGetDetailsResponse
    }

    /**
     * Test the property 'webUrl'
     */
    @Test
    public void webUrlTest() {
        // TODO: test webUrl
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'parallelRuns'
     */
    @Test
    public void parallelRunsTest() {
        // TODO: test parallelRuns
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'latestWorkflow'
     */
    @Test
    public void latestWorkflowTest() {
        // TODO: test latestWorkflow
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'executor'
     */
    @Test
    public void executorTest() {
        // TODO: test executor
    }

    /**
     * Test the property 'parallelism'
     */
    @Test
    public void parallelismTest() {
        // TODO: test parallelism
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'pipeline'
     */
    @Test
    public void pipelineTest() {
        // TODO: test pipeline
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'messages'
     */
    @Test
    public void messagesTest() {
        // TODO: test messages
    }

    /**
     * Test the property 'contexts'
     */
    @Test
    public void contextsTest() {
        // TODO: test contexts
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'queuedAt'
     */
    @Test
    public void queuedAtTest() {
        // TODO: test queuedAt
    }

    /**
     * Test the property 'stoppedAt'
     */
    @Test
    public void stoppedAtTest() {
        // TODO: test stoppedAt
    }

}
