/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InsightsGetJobTimeseriesDataResponseItemsInnerMetrics;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * InsightsGetJobTimeseriesDataResponseItemsInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class InsightsGetJobTimeseriesDataResponseItemsInner {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_MIN_STARTED_AT = "min_started_at";
  @SerializedName(SERIALIZED_NAME_MIN_STARTED_AT)
  private OffsetDateTime minStartedAt;

  public static final String SERIALIZED_NAME_MAX_ENDED_AT = "max_ended_at";
  @SerializedName(SERIALIZED_NAME_MAX_ENDED_AT)
  private OffsetDateTime maxEndedAt;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private OffsetDateTime timestamp;

  public static final String SERIALIZED_NAME_METRICS = "metrics";
  @SerializedName(SERIALIZED_NAME_METRICS)
  private InsightsGetJobTimeseriesDataResponseItemsInnerMetrics metrics;

  public InsightsGetJobTimeseriesDataResponseItemsInner() {
  }

  public InsightsGetJobTimeseriesDataResponseItemsInner name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * The name of the workflow.
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "build-and-test", required = true, value = "The name of the workflow.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public InsightsGetJobTimeseriesDataResponseItemsInner minStartedAt(OffsetDateTime minStartedAt) {
    
    
    
    
    this.minStartedAt = minStartedAt;
    return this;
  }

   /**
   * The start time for the earliest execution included in the metrics.
   * @return minStartedAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The start time for the earliest execution included in the metrics.")

  public OffsetDateTime getMinStartedAt() {
    return minStartedAt;
  }


  public void setMinStartedAt(OffsetDateTime minStartedAt) {
    
    
    
    this.minStartedAt = minStartedAt;
  }


  public InsightsGetJobTimeseriesDataResponseItemsInner maxEndedAt(OffsetDateTime maxEndedAt) {
    
    
    
    
    this.maxEndedAt = maxEndedAt;
    return this;
  }

   /**
   * The end time of the last execution included in the metrics.
   * @return maxEndedAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The end time of the last execution included in the metrics.")

  public OffsetDateTime getMaxEndedAt() {
    return maxEndedAt;
  }


  public void setMaxEndedAt(OffsetDateTime maxEndedAt) {
    
    
    
    this.maxEndedAt = maxEndedAt;
  }


  public InsightsGetJobTimeseriesDataResponseItemsInner timestamp(OffsetDateTime timestamp) {
    
    
    
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * The start of the interval for timeseries metrics.
   * @return timestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The start of the interval for timeseries metrics.")

  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(OffsetDateTime timestamp) {
    
    
    
    this.timestamp = timestamp;
  }


  public InsightsGetJobTimeseriesDataResponseItemsInner metrics(InsightsGetJobTimeseriesDataResponseItemsInnerMetrics metrics) {
    
    
    
    
    this.metrics = metrics;
    return this;
  }

   /**
   * Get metrics
   * @return metrics
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public InsightsGetJobTimeseriesDataResponseItemsInnerMetrics getMetrics() {
    return metrics;
  }


  public void setMetrics(InsightsGetJobTimeseriesDataResponseItemsInnerMetrics metrics) {
    
    
    
    this.metrics = metrics;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the InsightsGetJobTimeseriesDataResponseItemsInner instance itself
   */
  public InsightsGetJobTimeseriesDataResponseItemsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InsightsGetJobTimeseriesDataResponseItemsInner insightsGetJobTimeseriesDataResponseItemsInner = (InsightsGetJobTimeseriesDataResponseItemsInner) o;
    return Objects.equals(this.name, insightsGetJobTimeseriesDataResponseItemsInner.name) &&
        Objects.equals(this.minStartedAt, insightsGetJobTimeseriesDataResponseItemsInner.minStartedAt) &&
        Objects.equals(this.maxEndedAt, insightsGetJobTimeseriesDataResponseItemsInner.maxEndedAt) &&
        Objects.equals(this.timestamp, insightsGetJobTimeseriesDataResponseItemsInner.timestamp) &&
        Objects.equals(this.metrics, insightsGetJobTimeseriesDataResponseItemsInner.metrics)&&
        Objects.equals(this.additionalProperties, insightsGetJobTimeseriesDataResponseItemsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, minStartedAt, maxEndedAt, timestamp, metrics, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InsightsGetJobTimeseriesDataResponseItemsInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    minStartedAt: ").append(toIndentedString(minStartedAt)).append("\n");
    sb.append("    maxEndedAt: ").append(toIndentedString(maxEndedAt)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("min_started_at");
    openapiFields.add("max_ended_at");
    openapiFields.add("timestamp");
    openapiFields.add("metrics");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("min_started_at");
    openapiRequiredFields.add("max_ended_at");
    openapiRequiredFields.add("timestamp");
    openapiRequiredFields.add("metrics");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InsightsGetJobTimeseriesDataResponseItemsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!InsightsGetJobTimeseriesDataResponseItemsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InsightsGetJobTimeseriesDataResponseItemsInner is not found in the empty JSON string", InsightsGetJobTimeseriesDataResponseItemsInner.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InsightsGetJobTimeseriesDataResponseItemsInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the required field `metrics`
      InsightsGetJobTimeseriesDataResponseItemsInnerMetrics.validateJsonObject(jsonObj.getAsJsonObject("metrics"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InsightsGetJobTimeseriesDataResponseItemsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InsightsGetJobTimeseriesDataResponseItemsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InsightsGetJobTimeseriesDataResponseItemsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InsightsGetJobTimeseriesDataResponseItemsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<InsightsGetJobTimeseriesDataResponseItemsInner>() {
           @Override
           public void write(JsonWriter out, InsightsGetJobTimeseriesDataResponseItemsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InsightsGetJobTimeseriesDataResponseItemsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             InsightsGetJobTimeseriesDataResponseItemsInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InsightsGetJobTimeseriesDataResponseItemsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InsightsGetJobTimeseriesDataResponseItemsInner
  * @throws IOException if the JSON string is invalid with respect to InsightsGetJobTimeseriesDataResponseItemsInner
  */
  public static InsightsGetJobTimeseriesDataResponseItemsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InsightsGetJobTimeseriesDataResponseItemsInner.class);
  }

 /**
  * Convert an instance of InsightsGetJobTimeseriesDataResponseItemsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

