/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InsightsGetWorkflowSummaryMetricsResponseMetrics;
import com.konfigthis.client.model.InsightsGetWorkflowSummaryMetricsResponseTrends;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Workflow level aggregated metrics and trends response
 */
@ApiModel(description = "Workflow level aggregated metrics and trends response")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class InsightsGetWorkflowSummaryMetricsResponse {
  public static final String SERIALIZED_NAME_METRICS = "metrics";
  @SerializedName(SERIALIZED_NAME_METRICS)
  private InsightsGetWorkflowSummaryMetricsResponseMetrics metrics;

  public static final String SERIALIZED_NAME_TRENDS = "trends";
  @SerializedName(SERIALIZED_NAME_TRENDS)
  private InsightsGetWorkflowSummaryMetricsResponseTrends trends;

  public static final String SERIALIZED_NAME_WORKFLOW_NAMES = "workflow_names";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_NAMES)
  private List<String> workflowNames = new ArrayList<>();

  public InsightsGetWorkflowSummaryMetricsResponse() {
  }

  public InsightsGetWorkflowSummaryMetricsResponse metrics(InsightsGetWorkflowSummaryMetricsResponseMetrics metrics) {
    
    
    
    
    this.metrics = metrics;
    return this;
  }

   /**
   * Get metrics
   * @return metrics
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public InsightsGetWorkflowSummaryMetricsResponseMetrics getMetrics() {
    return metrics;
  }


  public void setMetrics(InsightsGetWorkflowSummaryMetricsResponseMetrics metrics) {
    
    
    
    this.metrics = metrics;
  }


  public InsightsGetWorkflowSummaryMetricsResponse trends(InsightsGetWorkflowSummaryMetricsResponseTrends trends) {
    
    
    
    
    this.trends = trends;
    return this;
  }

   /**
   * Get trends
   * @return trends
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public InsightsGetWorkflowSummaryMetricsResponseTrends getTrends() {
    return trends;
  }


  public void setTrends(InsightsGetWorkflowSummaryMetricsResponseTrends trends) {
    
    
    
    this.trends = trends;
  }


  public InsightsGetWorkflowSummaryMetricsResponse workflowNames(List<String> workflowNames) {
    
    
    
    
    this.workflowNames = workflowNames;
    return this;
  }

  public InsightsGetWorkflowSummaryMetricsResponse addWorkflowNamesItem(String workflowNamesItem) {
    this.workflowNames.add(workflowNamesItem);
    return this;
  }

   /**
   * A list of all the workflow names for a given project.
   * @return workflowNames
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A list of all the workflow names for a given project.")

  public List<String> getWorkflowNames() {
    return workflowNames;
  }


  public void setWorkflowNames(List<String> workflowNames) {
    
    
    
    this.workflowNames = workflowNames;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the InsightsGetWorkflowSummaryMetricsResponse instance itself
   */
  public InsightsGetWorkflowSummaryMetricsResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InsightsGetWorkflowSummaryMetricsResponse insightsGetWorkflowSummaryMetricsResponse = (InsightsGetWorkflowSummaryMetricsResponse) o;
    return Objects.equals(this.metrics, insightsGetWorkflowSummaryMetricsResponse.metrics) &&
        Objects.equals(this.trends, insightsGetWorkflowSummaryMetricsResponse.trends) &&
        Objects.equals(this.workflowNames, insightsGetWorkflowSummaryMetricsResponse.workflowNames)&&
        Objects.equals(this.additionalProperties, insightsGetWorkflowSummaryMetricsResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metrics, trends, workflowNames, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InsightsGetWorkflowSummaryMetricsResponse {\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    trends: ").append(toIndentedString(trends)).append("\n");
    sb.append("    workflowNames: ").append(toIndentedString(workflowNames)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("metrics");
    openapiFields.add("trends");
    openapiFields.add("workflow_names");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("metrics");
    openapiRequiredFields.add("trends");
    openapiRequiredFields.add("workflow_names");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InsightsGetWorkflowSummaryMetricsResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!InsightsGetWorkflowSummaryMetricsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InsightsGetWorkflowSummaryMetricsResponse is not found in the empty JSON string", InsightsGetWorkflowSummaryMetricsResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InsightsGetWorkflowSummaryMetricsResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `metrics`
      InsightsGetWorkflowSummaryMetricsResponseMetrics.validateJsonObject(jsonObj.getAsJsonObject("metrics"));
      // validate the required field `trends`
      InsightsGetWorkflowSummaryMetricsResponseTrends.validateJsonObject(jsonObj.getAsJsonObject("trends"));
      // ensure the required json array is present
      if (jsonObj.get("workflow_names") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("workflow_names").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `workflow_names` to be an array in the JSON string but got `%s`", jsonObj.get("workflow_names").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InsightsGetWorkflowSummaryMetricsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InsightsGetWorkflowSummaryMetricsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InsightsGetWorkflowSummaryMetricsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InsightsGetWorkflowSummaryMetricsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<InsightsGetWorkflowSummaryMetricsResponse>() {
           @Override
           public void write(JsonWriter out, InsightsGetWorkflowSummaryMetricsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InsightsGetWorkflowSummaryMetricsResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             InsightsGetWorkflowSummaryMetricsResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InsightsGetWorkflowSummaryMetricsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InsightsGetWorkflowSummaryMetricsResponse
  * @throws IOException if the JSON string is invalid with respect to InsightsGetWorkflowSummaryMetricsResponse
  */
  public static InsightsGetWorkflowSummaryMetricsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InsightsGetWorkflowSummaryMetricsResponse.class);
  }

 /**
  * Convert an instance of InsightsGetWorkflowSummaryMetricsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

