/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Test counts for a given pipeline number
 */
@ApiModel(description = "Test counts for a given pipeline number")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts {
  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private Long error;

  public static final String SERIALIZED_NAME_FAILURE = "failure";
  @SerializedName(SERIALIZED_NAME_FAILURE)
  private Long failure;

  public static final String SERIALIZED_NAME_SKIPPED = "skipped";
  @SerializedName(SERIALIZED_NAME_SKIPPED)
  private Long skipped;

  public static final String SERIALIZED_NAME_SUCCESS = "success";
  @SerializedName(SERIALIZED_NAME_SUCCESS)
  private Long success;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Long total;

  public InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts() {
  }

  public InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts error(Long error) {
    if (error != null && error < 0) {
      throw new IllegalArgumentException("Invalid value for error. Must be greater than or equal to 0.");
    }
    
    
    
    this.error = error;
    return this;
  }

   /**
   * The number of tests with the error status
   * minimum: 0
   * @return error
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of tests with the error status")

  public Long getError() {
    return error;
  }


  public void setError(Long error) {
    if (error != null && error < 0) {
      throw new IllegalArgumentException("Invalid value for error. Must be greater than or equal to 0.");
    }
    
    
    this.error = error;
  }


  public InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts failure(Long failure) {
    if (failure != null && failure < 0) {
      throw new IllegalArgumentException("Invalid value for failure. Must be greater than or equal to 0.");
    }
    
    
    
    this.failure = failure;
    return this;
  }

   /**
   * The number of tests with the failure status
   * minimum: 0
   * @return failure
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of tests with the failure status")

  public Long getFailure() {
    return failure;
  }


  public void setFailure(Long failure) {
    if (failure != null && failure < 0) {
      throw new IllegalArgumentException("Invalid value for failure. Must be greater than or equal to 0.");
    }
    
    
    this.failure = failure;
  }


  public InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts skipped(Long skipped) {
    if (skipped != null && skipped < 0) {
      throw new IllegalArgumentException("Invalid value for skipped. Must be greater than or equal to 0.");
    }
    
    
    
    this.skipped = skipped;
    return this;
  }

   /**
   * The number of tests with the skipped status
   * minimum: 0
   * @return skipped
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of tests with the skipped status")

  public Long getSkipped() {
    return skipped;
  }


  public void setSkipped(Long skipped) {
    if (skipped != null && skipped < 0) {
      throw new IllegalArgumentException("Invalid value for skipped. Must be greater than or equal to 0.");
    }
    
    
    this.skipped = skipped;
  }


  public InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts success(Long success) {
    if (success != null && success < 0) {
      throw new IllegalArgumentException("Invalid value for success. Must be greater than or equal to 0.");
    }
    
    
    
    this.success = success;
    return this;
  }

   /**
   * The number of tests with the success status
   * minimum: 0
   * @return success
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of tests with the success status")

  public Long getSuccess() {
    return success;
  }


  public void setSuccess(Long success) {
    if (success != null && success < 0) {
      throw new IllegalArgumentException("Invalid value for success. Must be greater than or equal to 0.");
    }
    
    
    this.success = success;
  }


  public InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts total(Long total) {
    if (total != null && total < 0) {
      throw new IllegalArgumentException("Invalid value for total. Must be greater than or equal to 0.");
    }
    
    
    
    this.total = total;
    return this;
  }

   /**
   * The total number of tests
   * minimum: 0
   * @return total
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The total number of tests")

  public Long getTotal() {
    return total;
  }


  public void setTotal(Long total) {
    if (total != null && total < 0) {
      throw new IllegalArgumentException("Invalid value for total. Must be greater than or equal to 0.");
    }
    
    
    this.total = total;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts instance itself
   */
  public InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts insightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts = (InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts) o;
    return Objects.equals(this.error, insightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.error) &&
        Objects.equals(this.failure, insightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.failure) &&
        Objects.equals(this.skipped, insightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.skipped) &&
        Objects.equals(this.success, insightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.success) &&
        Objects.equals(this.total, insightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.total)&&
        Objects.equals(this.additionalProperties, insightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, failure, skipped, success, total, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts {\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    failure: ").append(toIndentedString(failure)).append("\n");
    sb.append("    skipped: ").append(toIndentedString(skipped)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("error");
    openapiFields.add("failure");
    openapiFields.add("skipped");
    openapiFields.add("success");
    openapiFields.add("total");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("error");
    openapiRequiredFields.add("failure");
    openapiRequiredFields.add("skipped");
    openapiRequiredFields.add("success");
    openapiRequiredFields.add("total");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts is not found in the empty JSON string", InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.class));

       return (TypeAdapter<T>) new TypeAdapter<InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts>() {
           @Override
           public void write(JsonWriter out, InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
  * @throws IOException if the JSON string is invalid with respect to InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts
  */
  public static InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts.class);
  }

 /**
  * Convert an instance of InsightsGetProjectWorkflowTestMetricsResponseTestRunsInnerTestCounts to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

