/*
 * CircleCI API
 * This describes the resources that make up the CircleCI API v2.
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner;
import com.konfigthis.client.model.InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Project level test metrics response
 */
@ApiModel(description = "Project level test metrics response")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class InsightsGetProjectWorkflowTestMetricsResponse {
  public static final String SERIALIZED_NAME_AVERAGE_TEST_COUNT = "average_test_count";
  @SerializedName(SERIALIZED_NAME_AVERAGE_TEST_COUNT)
  private Long averageTestCount;

  public static final String SERIALIZED_NAME_MOST_FAILED_TESTS = "most_failed_tests";
  @SerializedName(SERIALIZED_NAME_MOST_FAILED_TESTS)
  private List<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner> mostFailedTests = new ArrayList<>();

  public static final String SERIALIZED_NAME_MOST_FAILED_TESTS_EXTRA = "most_failed_tests_extra";
  @SerializedName(SERIALIZED_NAME_MOST_FAILED_TESTS_EXTRA)
  private Long mostFailedTestsExtra;

  public static final String SERIALIZED_NAME_SLOWEST_TESTS = "slowest_tests";
  @SerializedName(SERIALIZED_NAME_SLOWEST_TESTS)
  private List<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner> slowestTests = new ArrayList<>();

  public static final String SERIALIZED_NAME_SLOWEST_TESTS_EXTRA = "slowest_tests_extra";
  @SerializedName(SERIALIZED_NAME_SLOWEST_TESTS_EXTRA)
  private Long slowestTestsExtra;

  public static final String SERIALIZED_NAME_TOTAL_TEST_RUNS = "total_test_runs";
  @SerializedName(SERIALIZED_NAME_TOTAL_TEST_RUNS)
  private Long totalTestRuns;

  public static final String SERIALIZED_NAME_TEST_RUNS = "test_runs";
  @SerializedName(SERIALIZED_NAME_TEST_RUNS)
  private List<InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner> testRuns = new ArrayList<>();

  public InsightsGetProjectWorkflowTestMetricsResponse() {
  }

  public InsightsGetProjectWorkflowTestMetricsResponse averageTestCount(Long averageTestCount) {
    if (averageTestCount != null && averageTestCount < 0) {
      throw new IllegalArgumentException("Invalid value for averageTestCount. Must be greater than or equal to 0.");
    }
    
    
    
    this.averageTestCount = averageTestCount;
    return this;
  }

   /**
   * The average number of tests executed per run
   * minimum: 0
   * @return averageTestCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The average number of tests executed per run")

  public Long getAverageTestCount() {
    return averageTestCount;
  }


  public void setAverageTestCount(Long averageTestCount) {
    if (averageTestCount != null && averageTestCount < 0) {
      throw new IllegalArgumentException("Invalid value for averageTestCount. Must be greater than or equal to 0.");
    }
    
    
    this.averageTestCount = averageTestCount;
  }


  public InsightsGetProjectWorkflowTestMetricsResponse mostFailedTests(List<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner> mostFailedTests) {
    
    
    
    
    this.mostFailedTests = mostFailedTests;
    return this;
  }

  public InsightsGetProjectWorkflowTestMetricsResponse addMostFailedTestsItem(InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner mostFailedTestsItem) {
    this.mostFailedTests.add(mostFailedTestsItem);
    return this;
  }

   /**
   * Metrics for the most frequently failing tests
   * @return mostFailedTests
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Metrics for the most frequently failing tests")

  public List<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner> getMostFailedTests() {
    return mostFailedTests;
  }


  public void setMostFailedTests(List<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner> mostFailedTests) {
    
    
    
    this.mostFailedTests = mostFailedTests;
  }


  public InsightsGetProjectWorkflowTestMetricsResponse mostFailedTestsExtra(Long mostFailedTestsExtra) {
    if (mostFailedTestsExtra != null && mostFailedTestsExtra < 0) {
      throw new IllegalArgumentException("Invalid value for mostFailedTestsExtra. Must be greater than or equal to 0.");
    }
    
    
    
    this.mostFailedTestsExtra = mostFailedTestsExtra;
    return this;
  }

   /**
   * The number of tests with the same success rate being omitted from most_failed_tests
   * minimum: 0
   * @return mostFailedTestsExtra
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of tests with the same success rate being omitted from most_failed_tests")

  public Long getMostFailedTestsExtra() {
    return mostFailedTestsExtra;
  }


  public void setMostFailedTestsExtra(Long mostFailedTestsExtra) {
    if (mostFailedTestsExtra != null && mostFailedTestsExtra < 0) {
      throw new IllegalArgumentException("Invalid value for mostFailedTestsExtra. Must be greater than or equal to 0.");
    }
    
    
    this.mostFailedTestsExtra = mostFailedTestsExtra;
  }


  public InsightsGetProjectWorkflowTestMetricsResponse slowestTests(List<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner> slowestTests) {
    
    
    
    
    this.slowestTests = slowestTests;
    return this;
  }

  public InsightsGetProjectWorkflowTestMetricsResponse addSlowestTestsItem(InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner slowestTestsItem) {
    this.slowestTests.add(slowestTestsItem);
    return this;
  }

   /**
   * Metrics for the slowest running tests
   * @return slowestTests
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Metrics for the slowest running tests")

  public List<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner> getSlowestTests() {
    return slowestTests;
  }


  public void setSlowestTests(List<InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner> slowestTests) {
    
    
    
    this.slowestTests = slowestTests;
  }


  public InsightsGetProjectWorkflowTestMetricsResponse slowestTestsExtra(Long slowestTestsExtra) {
    if (slowestTestsExtra != null && slowestTestsExtra < 0) {
      throw new IllegalArgumentException("Invalid value for slowestTestsExtra. Must be greater than or equal to 0.");
    }
    
    
    
    this.slowestTestsExtra = slowestTestsExtra;
    return this;
  }

   /**
   * The number of tests with the same duration rate being omitted from slowest_tests
   * minimum: 0
   * @return slowestTestsExtra
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The number of tests with the same duration rate being omitted from slowest_tests")

  public Long getSlowestTestsExtra() {
    return slowestTestsExtra;
  }


  public void setSlowestTestsExtra(Long slowestTestsExtra) {
    if (slowestTestsExtra != null && slowestTestsExtra < 0) {
      throw new IllegalArgumentException("Invalid value for slowestTestsExtra. Must be greater than or equal to 0.");
    }
    
    
    this.slowestTestsExtra = slowestTestsExtra;
  }


  public InsightsGetProjectWorkflowTestMetricsResponse totalTestRuns(Long totalTestRuns) {
    if (totalTestRuns != null && totalTestRuns < 0) {
      throw new IllegalArgumentException("Invalid value for totalTestRuns. Must be greater than or equal to 0.");
    }
    
    
    
    this.totalTestRuns = totalTestRuns;
    return this;
  }

   /**
   * The total number of test runs
   * minimum: 0
   * @return totalTestRuns
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The total number of test runs")

  public Long getTotalTestRuns() {
    return totalTestRuns;
  }


  public void setTotalTestRuns(Long totalTestRuns) {
    if (totalTestRuns != null && totalTestRuns < 0) {
      throw new IllegalArgumentException("Invalid value for totalTestRuns. Must be greater than or equal to 0.");
    }
    
    
    this.totalTestRuns = totalTestRuns;
  }


  public InsightsGetProjectWorkflowTestMetricsResponse testRuns(List<InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner> testRuns) {
    
    
    
    
    this.testRuns = testRuns;
    return this;
  }

  public InsightsGetProjectWorkflowTestMetricsResponse addTestRunsItem(InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner testRunsItem) {
    this.testRuns.add(testRunsItem);
    return this;
  }

   /**
   * Test counts grouped by pipeline number and workflow id
   * @return testRuns
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Test counts grouped by pipeline number and workflow id")

  public List<InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner> getTestRuns() {
    return testRuns;
  }


  public void setTestRuns(List<InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner> testRuns) {
    
    
    
    this.testRuns = testRuns;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the InsightsGetProjectWorkflowTestMetricsResponse instance itself
   */
  public InsightsGetProjectWorkflowTestMetricsResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InsightsGetProjectWorkflowTestMetricsResponse insightsGetProjectWorkflowTestMetricsResponse = (InsightsGetProjectWorkflowTestMetricsResponse) o;
    return Objects.equals(this.averageTestCount, insightsGetProjectWorkflowTestMetricsResponse.averageTestCount) &&
        Objects.equals(this.mostFailedTests, insightsGetProjectWorkflowTestMetricsResponse.mostFailedTests) &&
        Objects.equals(this.mostFailedTestsExtra, insightsGetProjectWorkflowTestMetricsResponse.mostFailedTestsExtra) &&
        Objects.equals(this.slowestTests, insightsGetProjectWorkflowTestMetricsResponse.slowestTests) &&
        Objects.equals(this.slowestTestsExtra, insightsGetProjectWorkflowTestMetricsResponse.slowestTestsExtra) &&
        Objects.equals(this.totalTestRuns, insightsGetProjectWorkflowTestMetricsResponse.totalTestRuns) &&
        Objects.equals(this.testRuns, insightsGetProjectWorkflowTestMetricsResponse.testRuns)&&
        Objects.equals(this.additionalProperties, insightsGetProjectWorkflowTestMetricsResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(averageTestCount, mostFailedTests, mostFailedTestsExtra, slowestTests, slowestTestsExtra, totalTestRuns, testRuns, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InsightsGetProjectWorkflowTestMetricsResponse {\n");
    sb.append("    averageTestCount: ").append(toIndentedString(averageTestCount)).append("\n");
    sb.append("    mostFailedTests: ").append(toIndentedString(mostFailedTests)).append("\n");
    sb.append("    mostFailedTestsExtra: ").append(toIndentedString(mostFailedTestsExtra)).append("\n");
    sb.append("    slowestTests: ").append(toIndentedString(slowestTests)).append("\n");
    sb.append("    slowestTestsExtra: ").append(toIndentedString(slowestTestsExtra)).append("\n");
    sb.append("    totalTestRuns: ").append(toIndentedString(totalTestRuns)).append("\n");
    sb.append("    testRuns: ").append(toIndentedString(testRuns)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("average_test_count");
    openapiFields.add("most_failed_tests");
    openapiFields.add("most_failed_tests_extra");
    openapiFields.add("slowest_tests");
    openapiFields.add("slowest_tests_extra");
    openapiFields.add("total_test_runs");
    openapiFields.add("test_runs");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("average_test_count");
    openapiRequiredFields.add("most_failed_tests");
    openapiRequiredFields.add("most_failed_tests_extra");
    openapiRequiredFields.add("slowest_tests");
    openapiRequiredFields.add("slowest_tests_extra");
    openapiRequiredFields.add("total_test_runs");
    openapiRequiredFields.add("test_runs");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InsightsGetProjectWorkflowTestMetricsResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!InsightsGetProjectWorkflowTestMetricsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InsightsGetProjectWorkflowTestMetricsResponse is not found in the empty JSON string", InsightsGetProjectWorkflowTestMetricsResponse.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InsightsGetProjectWorkflowTestMetricsResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (!jsonObj.get("most_failed_tests").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `most_failed_tests` to be an array in the JSON string but got `%s`", jsonObj.get("most_failed_tests").toString()));
      }

      JsonArray jsonArraymostFailedTests = jsonObj.getAsJsonArray("most_failed_tests");
      // validate the required field `most_failed_tests` (array)
      for (int i = 0; i < jsonArraymostFailedTests.size(); i++) {
        InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner.validateJsonObject(jsonArraymostFailedTests.get(i).getAsJsonObject());
      };
      // ensure the json data is an array
      if (!jsonObj.get("slowest_tests").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `slowest_tests` to be an array in the JSON string but got `%s`", jsonObj.get("slowest_tests").toString()));
      }

      JsonArray jsonArrayslowestTests = jsonObj.getAsJsonArray("slowest_tests");
      // validate the required field `slowest_tests` (array)
      for (int i = 0; i < jsonArrayslowestTests.size(); i++) {
        InsightsGetProjectWorkflowTestMetricsResponseMostFailedTestsInner.validateJsonObject(jsonArrayslowestTests.get(i).getAsJsonObject());
      };
      // ensure the json data is an array
      if (!jsonObj.get("test_runs").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `test_runs` to be an array in the JSON string but got `%s`", jsonObj.get("test_runs").toString()));
      }

      JsonArray jsonArraytestRuns = jsonObj.getAsJsonArray("test_runs");
      // validate the required field `test_runs` (array)
      for (int i = 0; i < jsonArraytestRuns.size(); i++) {
        InsightsGetProjectWorkflowTestMetricsResponseTestRunsInner.validateJsonObject(jsonArraytestRuns.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InsightsGetProjectWorkflowTestMetricsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InsightsGetProjectWorkflowTestMetricsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InsightsGetProjectWorkflowTestMetricsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InsightsGetProjectWorkflowTestMetricsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<InsightsGetProjectWorkflowTestMetricsResponse>() {
           @Override
           public void write(JsonWriter out, InsightsGetProjectWorkflowTestMetricsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InsightsGetProjectWorkflowTestMetricsResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             InsightsGetProjectWorkflowTestMetricsResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InsightsGetProjectWorkflowTestMetricsResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InsightsGetProjectWorkflowTestMetricsResponse
  * @throws IOException if the JSON string is invalid with respect to InsightsGetProjectWorkflowTestMetricsResponse
  */
  public static InsightsGetProjectWorkflowTestMetricsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InsightsGetProjectWorkflowTestMetricsResponse.class);
  }

 /**
  * Convert an instance of InsightsGetProjectWorkflowTestMetricsResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

